apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: "./manifests"  # Path to the manifests directory relative to flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system  # Name of the GitRepository that you set earlier
