apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: manifests
  namespace: flux-system
spec:
  interval: 10m
  path: "../../manifests"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
