apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: manifests  # Ensure this name is "manifests"
  namespace: flux-system
spec:
  interval: 10m
  path: "../../manifests"  # Path relative to this kustomization file
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
